# Generated by Django 4.1.7 on 2023-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aop_lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('English', 'English')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aop_sub_lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('BL', 'BL'), ('ML1', 'ML1'), ('ML2', 'ML2'), ('EL', 'EL')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='option',
            field=models.CharField(choices=[('General Program', 'General Program'), ('AOP Program', 'AOP Program'), ('Advance English Program', 'Advance English Program')], max_length=50),
        ),
    ]
